// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Body: typeof import('./src/components/Body.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBudge: typeof import('element-plus/es')['ElBudge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    Header: typeof import('./src/components/Header.vue')['default']
    Item: typeof import('./src/components/Item.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
